### ISSUE TITLE
Metacritic scores now display next to titles on IMDB

### ISSUE THREAD

**Issue by ikingjosh** [ganigeorgiev/hide-ratings-extension#11]
Hi,  this has been a great app, thanks so much.  Just thought I'd mention that Imdb now displays metacritic scores next to their titles.  I was wondering if you're considering an update to the extension to block that as well.  Would be great,  thanks again.
Josh K

**Comment by ganigeorgiev** [comment]
Should be fixed with v2.2.0 of the extension (at least at the places I could find it; if after the update you are still seeing the meta ratings, please post a link to the specific page).

I've submitted it for review but it may take some time to show up in the Chrome Web Store. Usually the browser will update the extension automatically once the new version is approved but if it doesn't happen you can manually trigger an update from the [`chrome://extensions`](chrome://extensions) page and click on the "Update" button.

Note that there are some sections in the IMDB website where ratings will still be visible because they are loaded with iframe (ex. [Staff picks](https://www.imdb.com/imdbpicks/staff-picks/)). Fixing it will require loading additional JS to apply the extension styles and I want to avoid that for now.

**Comment by ikingjosh** [comment]
Yeah the main place I was thinking of was the Metacritic score showing on a person's IMDb watchlist page.  Glad you've already thought about it.

Thanks for the update, and the great idea to do this in the first place!
